apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jimeng-api-data
  namespace: __NAMESPACE__
  labels:
    app.kubernetes.io/name: jimeng-api
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: __STORAGE_CLASS__
  resources:
    requests:
      storage: __STORAGE_SIZE__
