apiVersion: v1
kind: Service
metadata:
  name: jimeng-api
  namespace: __NAMESPACE__
  labels:
    app.kubernetes.io/name: jimeng-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: jimeng-api
  ports:
    - name: http
      port: 5100
      targetPort: http
